plots_default_params:
    figure.figsize: [20, 8]
    font.size: 20
    lines.linewidth: 5
    lines.markersize: 15
optimizator:
    data:
        path_to_data: data/owid-covid-data.csv
        dropna_subset: [reproduction_rate]
        locations: [Italy, Germany, Russia, United Kingdom]
        columns: [location, date, total_cases, reproduction_rate, population]
        max_date: 2021-12-31
    n_runs: 1000
    model_name: ISI
    metric_name: mean_absolute_percentage_error
    optimizator_name: Nelder-Mead
    test_ratio: 0.2
    dt: 1
    seed: 42
    path_to_results: results