SI:
    constraints:
        b: [0, 2]
ISI:
    constraints:
        b0: [0, 1.25]
        db: [0, 1.25]
        k: [0, 1.25]
        bss: [0, 1.25]
        bls: [0, 1.25]
        Tss: [1, 90]
        Tls: [90, 1000]
        wss: [0, 3.1415]
        wls: [0, 3.1415]